@startuml Cartas

    interface CartaDesarrollo {
        + ejecutarAlGuardar(Jugador): void
        + getCarta(): String
    }

    class Caballero implements CartaDesarrollo {
        - juego: Juego
        - nuevoLugar: Hexagono
        - victima: Jugador
        - jugadorActual: Jugador
        + Caballero(Juego, Hexagono, Jugador, Jugador)
        + ejecutarAlGuardar(Jugador): void
        + ejecutar(): void
        + getCarta(): String
    }

    class PuntoVictoria implements CartaDesarrollo {
        + ejecutarAlGuardar(Jugador): void
        + ejecutar(): void
        + getCarta(): String
    }

    class ProgresoConstruccion implements CartaDesarrollo {
        - juego: Juego
        - jugadorActual: Jugador
        - carreteraAConstruir: List<Arista>
        + ProgresoConstruccion(Juego, Jugador, List<Arista>)
        + ejecutarAlGuardar(Jugador): void
        + ejecutar(): void
        + getCarta(): String
    }

    class ProgresoDescubrimiento implements CartaDesarrollo {
        - jugadorActual: Jugador
        - recursosDeBanca: List<Recurso>
        + ProgresoDescubrimiento(Jugador, List<Recurso>)
        + ejecutarAlGuardar(Jugador): void
        + ejecutar(): void
        + getCarta(): String
    }

    class ProgresoMonopolio implements CartaDesarrollo {
        - juego: Juego
        - recursoDeseado: Recurso
        - jugadorActual: Jugador
        + ProgresoMonopolio(Juego, Recurso, Jugador)
        + ejecutarAlGuardar(Jugador): void
        + ejecutar(): void
        + getCarta(): String
    }

    class FabricaCartas {
        - VER hay cosas comentadas
        + {static} crearMazo(): List<CartaDesarrollo>
    }

    interface CartaBonificacion {
        + evaluarCartaBonificacion(Jugador, Tablero): void
    }

    class GranCaballeria implements CartaBonificacion {
        - dueño: Jugador
        - mayorEjercito: int
        - yaOtorgada: bool
        + evaluarCartaBonificacion(Jugador, Tablero): void
    }

    class GranRutaComercial implements CartaBonificacion {
        - dueño: Jugador
        - mayorRutaComercial: int
        - yaOtorgada: bool
        + evaluarCartaBonificacion(Jugador, Tablero): void
    }
    
FabricaCartas ..> CartaDesarrollo : "crea"


@enduml