@startuml

class Bosque { 
    + producirPara(Construccion): void
    + aceptar(Visitante): int
    + colocarLadron(Hexagono): void
    + getTerreno(): String
}
class Campo {
    + producirPara(Construccion): void
    + aceptar(Visitante): int
    + colocarLadron(Hexagono): void
    + getTerreno(): String
}
class Colina {
    + producirPara(Construccion): void
    + aceptar(Visitante): int
    + colocarLadron(Hexagono): void
    + getTerreno(): String
}
class Desierto {
    + producirPara(Construccion): void
    + aceptar(Visitante): int
    + colocarLadron(Hexagono): void
    + getTerreno(): String
}
class Montaña {
    + producirPara(Construccion): void
    + aceptar(Visitante): int
    + colocarLadron(Hexagono): void
    + getTerreno(): String
}
class Pastizal {
    + producirPara(Construccion): void
    + aceptar(Visitante): int
    + colocarLadron(Hexagono): void
    + getTerreno(): String
}
interface Terreno {
    + producirPara(Construccion): void
    + aceptar(Visitante): int
    + colocarLadron(Hexagono): void
    + getTerreno(): String
}

Terreno <|.. Bosque
Terreno <|.. Campo
Terreno <|.. Colina
Terreno <|.. Desierto
Terreno <|.. Montaña
Terreno <|.. Pastizal

@enduml
