@startuml excepciones_comercio

class RuntimeException {
}

class ComercioInvalidoError extends RuntimeException {
    + ComercioInvalidoError(String message)
}

class RecursosInsuficientesError extends RuntimeException {
    + RecursosInsuficientesError(String mensaje)
}



@enduml
